services:
  server:
    build: ./server
    ports:
      - '8080:8080'
    env_file:
      - ./server/.env
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
